---

name: Build and test

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros: melodic
            ros_major: 1
          - ros: noetic
            ros_major: 1
          - ros: foxy
            ros_major: 2
          - ros: humble
            ros_major: 2
          - ros: jazzy
            ros_major: 2
          - ros: kilted
            ros_major: 2
          - ros: rolling
            ros_major: 2
    name: ROS ${{ matrix.ros }}
    container:
      image: polymathrobotics/ros:${{ matrix.ros }}-builder-ubuntu

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
            libboost-all-dev \
            libyaml-cpp-dev

      - id: ros1_ci
        if: ${{ matrix.ros_major == 1 }}
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros1-distro: ${{ matrix.ros }}
          coverage-result: false
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                  "-DCMAKE_CXX_FLAGS=-Werror"
                ]
              }
            }

      - id: ros2_ci
        if: ${{ matrix.ros_major == 2 }}
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: ${{ matrix.ros }}
          coverage-result: false
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                  "-DCMAKE_CXX_FLAGS=-Werror"
                ]
              }
            }

      - name: Upload ROS 1 colcon logs
        if: ${{ always() && matrix.ros_major == 1 }}
        uses: actions/upload-artifact@v4
        with:
          name: colcon-logs-${{ matrix.ros }}
          path: ${{ steps.ros1_ci.outputs.ros-workspace-directory-name }}/log

      - name: Upload ROS 2 colcon logs
        if: ${{ always() && matrix.ros_major == 2 }}
        uses: actions/upload-artifact@v4
        with:
          name: colcon-logs-${{ matrix.ros }}
          path: ${{ steps.ros2_ci.outputs.ros-workspace-directory-name }}/log