---

name: Build and test
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros: [humble, jazzy, kilted, rolling]
    name: ROS 2 ${{ matrix.ros }}
    container:
      image: polymathrobotics/ros:${{ matrix.ros }}-builder-ubuntu
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: ${{ matrix.ros }}
          coverage-result: false
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                  "-DCMAKE_CXX_FLAGS=-Werror"
                ]
              }
            }
      - uses: actions/upload-artifact@v4
        with:
          name: colcon-logs-${{ matrix.ros }}
          path: ros_ws/log
